
import React from 'react';

const DbSetup: React.FC = () => {
  const SQL_SCHEMA = `
-- Create profiles table
create table public.profiles (
  id uuid references auth.users not null primary key,
  name text not null,
  handle text,
  img text,
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create bills table
create table public.bills (
  id bigint generated by default as identity primary key,
  title text not null,
  amount numeric not null,
  description text,
  date text,
  status text,
  category text,
  payer_id uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create bill participants table
create table public.bill_participants (
  id bigint generated by default as identity primary key,
  bill_id bigint references public.bills(id) on delete cascade,
  user_id uuid references public.profiles(id),
  amount numeric not null,
  paid boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create receipt items table
create table public.receipt_items (
  id bigint generated by default as identity primary key,
  bill_id bigint references public.bills(id) on delete cascade,
  name text not null,
  price numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create groups table
create table public.groups (
  id bigint generated by default as identity primary key,
  name text not null,
  img text,
  created_by uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create group members table
create table public.group_members (
  id bigint generated by default as identity primary key,
  group_id bigint references public.groups(id) on delete cascade,
  user_id uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(group_id, user_id)
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.bills enable row level security;
alter table public.bill_participants enable row level security;
alter table public.receipt_items enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;

-- Create policies (simplified for demo: public access)
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);

create policy "Bills are viewable by everyone." on public.bills for select using (true);
create policy "Authenticated users can insert bills." on public.bills for insert with check (auth.role() = 'authenticated');

create policy "Bill participants are viewable by everyone." on public.bill_participants for select using (true);
create policy "Authenticated users can insert participants." on public.bill_participants for insert with check (auth.role() = 'authenticated');
create policy "Participants can update their own status." on public.bill_participants for update using (auth.uid() = user_id);

create policy "Receipt items are viewable by everyone." on public.receipt_items for select using (true);
create policy "Authenticated users can insert items." on public.receipt_items for insert with check (auth.role() = 'authenticated');

create policy "Groups are viewable by everyone." on public.groups for select using (true);
create policy "Authenticated users can insert groups." on public.groups for insert with check (auth.role() = 'authenticated');

create policy "Group members are viewable by everyone." on public.group_members for select using (true);
create policy "Authenticated users can insert group members." on public.group_members for insert with check (auth.role() = 'authenticated');
`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(SQL_SCHEMA);
    alert('SQL copied to clipboard!');
  };

  return (
    <div className="flex min-h-screen w-full flex-col bg-background-dark text-white p-6 font-display">
      <div className="flex-1 flex flex-col items-center justify-center max-w-2xl mx-auto text-center">
        <span className="material-symbols-outlined text-6xl text-primary mb-6">database</span>
        <h1 className="text-3xl font-bold mb-4">Database Setup Required</h1>
        <p className="text-white/70 mb-8">
          Your Supabase project is connected, but the required tables are missing. 
          Please run the following SQL schema in your Supabase SQL Editor.
        </p>

        <div className="w-full bg-black/30 rounded-xl border border-white/10 p-4 text-left overflow-hidden relative group">
          <pre className="text-xs text-slate-300 overflow-x-auto h-64 font-mono">
            {SQL_SCHEMA}
          </pre>
          <div className="absolute top-2 right-2">
            <button 
              onClick={copyToClipboard}
              className="bg-primary text-black text-xs font-bold px-3 py-2 rounded-lg hover:bg-primary/90 transition-colors"
            >
              Copy SQL
            </button>
          </div>
        </div>

        <div className="mt-8 flex flex-col gap-4 w-full max-w-sm">
            <button 
                onClick={() => window.location.reload()}
                className="w-full bg-white/10 hover:bg-white/20 text-white font-bold py-3 rounded-xl transition-colors border border-white/10"
            >
                I've run the SQL, Reload App
            </button>
            <a 
                href="https://supabase.com/dashboard/project/_/sql/new" 
                target="_blank"
                rel="noreferrer"
                className="text-primary text-sm hover:underline"
            >
                Open Supabase SQL Editor &rarr;
            </a>
        </div>
      </div>
    </div>
  );
};

export default DbSetup;
